spring.application.name=presence-service
server.port=8083

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT (mesmo secret do UserService e AccessControl)
security.jwt.secret=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=

# TTL de sessão (alterar aqui para ajustar limpeza automática)
presence.session.ttl-hours=6
