# This file should not be commited in a real scenario

apiVersion: v1
kind: Secret
metadata:
  name: gymmonitor-secrets
  labels:
    {{- include "gymmonitor.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: TURFeU16UTFOamM0T1dGaVkyUmxaakF4TWpNME5UWTNPRGxoWW1Oa1pXWT0=
  postgres-password: Z3ltbW9uaXRvcl9wYXNz
