apiVersion: v1
kind: Service
metadata:
  name: presence-service
  labels:
    {{- include "gymmonitor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: presence-service
  ports:
    - port: 8083
      targetPort: 8083
